#!/usr/bin/env python3
"""Validate the portable contract and generate the CLI identity manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import tempfile
from pathlib import Path


CAPABILITY_NAME = re.compile(r"^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$")
CAPABILITY_VERSION = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")
DEFAULT_OUTPUT = Path("src/generated/action-capabilities.ts")


def expected_fingerprint(name: str, version: str) -> str:
    source = f"miosa-capability/{name}@{version}".encode()
    return f"sha256:{hashlib.sha256(source).hexdigest()}"


def identities(contract: dict) -> list[dict[str, str]]:
    if set(contract) != {"version", "capabilities"} or contract.get("version") != 1:
        raise ValueError("unsupported action capability contract")

    result = []
    for capability in contract.get("capabilities", []):
        if set(capability) != {"name", "version", "fingerprint", "surfaces"}:
            raise ValueError("portable contract contains policy or unsupported fields")
        name = capability.get("name")
        version = capability.get("version")
        fingerprint = capability.get("fingerprint")
        if not isinstance(name, str) or not CAPABILITY_NAME.fullmatch(name):
            raise ValueError(f"invalid capability name: {name!r}")
        if not isinstance(version, str) or not CAPABILITY_VERSION.fullmatch(version):
            raise ValueError(f"invalid capability version: {version!r}")
        if fingerprint != expected_fingerprint(name, version):
            raise ValueError(f"invalid capability fingerprint: {name}")
        result.append(
            {"name": name, "version": version, "fingerprint": fingerprint}
        )

    names = [identity["name"] for identity in result]
    if not names or names != sorted(names) or len(names) != len(set(names)):
        raise ValueError("capability identities must be nonempty, unique, and sorted")
    return result


def render(rows: list[dict[str, str]]) -> str:
    payload = json.dumps(rows, indent=2)
    return (
        "// Generated by scripts/sync-action-capabilities.py.\n"
        "// Authorization policy remains server-owned in MIOSA Compute.\n"
        f"export const ACTION_CAPABILITY_IDENTITIES = {payload} as const;\n"
    )


def write_atomic(path: Path, contents: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=path.name, dir=path.parent)
    try:
        with os.fdopen(descriptor, "w") as handle:
            handle.write(contents)
        os.chmod(temporary, 0o644)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    rows = identities(json.loads(args.source.read_text()))
    contents = render(rows)
    if args.check:
        if not args.output.exists() or args.output.read_text() != contents:
            raise SystemExit(f"{args.output} is stale; run {Path(__file__).name}")
        return
    write_atomic(args.output, contents)


if __name__ == "__main__":
    main()
